### ISSUE TITLE
Bitmap performance issues in finding continuous memory space

### ISSUE THREAD

**Issue by leeq2016** [cxl-micron-reskit/famfs#68]
When FAMFS_ALLOC_UNIT is adjusted to 4K, bitmap search becomes a bottleneck when famfs cp copies a large number of files.

perf log:
+   60.06%  famfs    famfs              [.] mu_bitmap_test
+   37.18%  famfs    famfs              [.] bitmap_alloc_contiguous

**Comment by jagalactic** [comment]
Merged fix in PR #69 

This won't be the last allocator performance work we do, but it helps.
